/// Generated by AssetsRefGenerator on 2021/06/04
class Res {
  static const String dt = "assets/image/dt.png";
  static const String ic_no_data = "assets/image/ic_no_data.webp";
  static const String note = "assets/image/note.png";
  static const String wj = "assets/image/wj.png";
  static const String wj_cat = "assets/image/wj_cat.png";
}
