/// Generated by AssetsRefGenerator on 2021/03/03
class Res {
  static const String dt = "assets/dt.png";
  static const String note = "assets/note.png";
  static const String wj = "assets/wj.png";
  static const String wj_cat = "assets/wj_cat.png";
}
